In [2]:
import pandas as pd
import numpy as np
# Read-in data
data=pd.read_csv("titanic_traning.csv")

In [3]:
## Take a look at missing and inconsistency values:
print(data['pclass'].unique())
print(data['sex'].unique())    # inconsistency
print(data['age'].unique())    # missing values
print(data['sibsp'].unique())
print(data['parch'].unique())
print(data['fare'].unique())     # missing values
print(data['embarked'].unique())  # inconsistency
print(data['survived'].unique())

[3 2 1]
['male' 'female' 'Male' 'Female']
[20.     18.         nan  2.     45.     50.     44.     23.     25.
 22.     30.     55.     32.     26.     37.     28.     41.     35.
 27.     36.     47.      8.     29.     21.     19.     53.     31.
 12.     39.     63.     32.5    55.5    38.     34.     42.     17.
 33.     24.     48.     16.     49.      4.     40.      9.     15.
  6.     51.     43.      0.9167  0.4167 11.     52.     60.     60.5
 38.5     5.     24.5     7.     61.     14.5    20.5    14.     74.
 36.5    57.      3.     65.     64.     54.     18.5    80.     45.5
  0.8333 46.     59.      1.     30.5    62.     11.5    67.     58.
  0.75   56.     28.5    34.5    70.      0.6667 71.      0.3333 13.
 10.     76.      0.1667 26.5    70.5   ]
[0 3 1 2 5 8 4]
[0 2 1 3 5 6 4 9]
[  4.    7.2  15.6   0.   27.9  29.7 106.4  10.5   nan 263.    7.7 151.6
  23.3  57.8 135.6  22.5   7.9  26.   83.2  23.5  13.5  31.    7.8  21.
  39.   52.6  15.   26.3  55.4  75.2  12.4  1

In [4]:
#missing value of age
pd.isnull(data["age"])
c1=sum(pd.isnull(data["age"]))
c1p="{0:.2%}".format(c1/916)
#missing value of fare
pd.isnull(data["fare"])
c2=sum(pd.isnull(data["fare"]))
c2p="{0:.2%}".format(c2/916)

In [5]:
#inconsistent value of sex
x1=np.sum(data["sex"]=='Male')
x2=np.sum(data["sex"]=='Female')
x3=x1+x2 
x3p="{0:.2%}".format(x3/916) 

#inconsistent value of embarked
data["embarked"]=='Queenstown'
x4=np.sum(data["embarked"]=='Queenstown')
x4p="{0:.2%}".format(x4/916) 

In [6]:
#generate a table of missing value and inconsistent value
print('Features','MV','%ofMV','IV','%ofIV')
print('pclass  ',0.00,0.00,0.00,0.00)
print('sex     ',0.00,0.00,x3,x3p)
print('age     ',c1,c1p,0.00,0.00)
print('sibsp   ',0.00,0.00,0.00,0.00)
print('parch   ',0.00,0.00,0.00,0.00)
print('fare    ',c2,c2p,0.00,0.00)
print('embarked',0.00,0.00,x4,x4p)
print('survived',0.00,0.00,0.00,0.00)

Features MV %ofMV IV %ofIV
pclass   0.0 0.0 0.0 0.0
sex      0.0 0.0 4 0.44%
age      188 20.52% 0.0 0.0
sibsp    0.0 0.0 0.0 0.0
parch    0.0 0.0 0.0 0.0
fare     9 0.98% 0.0 0.0
embarked 0.0 0.0 3 0.33%
survived 0.0 0.0 0.0 0.0


In [6]:
#List/Display all the records with missing value(s) and/or inconsistent value(s).
print(data[data['age'].isnull()])
print(data[data['fare'].isnull()])

print(data[data['sex'].isin(['Male','Female'])])
print(data[data.embarked =='Queenstown'])

      ID  pclass     sex  age  sibsp  parch   fare    embarked  survived
2      3       2    male  NaN      0      0   15.6           C         0
3      4       2    male  NaN      0      0    0.0           S         0
11    12       3  female  NaN      0      0    7.7           Q         1
13    14       3  female  NaN      2      0   23.3           Q         1
18    19       1    male  NaN      0      0   26.0           S         0
21    22       3    male  NaN      1      2   23.5           S         0
37    38       3  female  NaN      0      0    7.8           Q         1
41    42       2  female  NaN      0      0   12.4           Q         1
43    44       3    male  NaN      0      0    7.3           S         0
63    64       3    male  NaN      0      0    7.8           Q         0
76    77       3    male  NaN      0      0    8.1           S         0
79    80       3    male  NaN      1      1   15.2           C         1
85    86       3    male  NaN      1      0   14.5 

In [7]:
#Handle the missing values 
Newdata = pd.read_csv("titanic_traning.csv")
changeforage = pd.DataFrame(data.age)  # work on the missing values of age
CFA = changeforage.fillna(data.mean())
Newdata.age = CFA

changeforfare = pd.DataFrame(data.fare)  # work on the missing values of fare
CFF = changeforfare.fillna(data.mean())
Newdata.fare = CFF

In [8]:
#Correct the data inconsistency issue
changeforsex = pd.DataFrame(data.sex)  # work on the inconsistency of sex
CFS = changeforsex.replace({'sex': {'Male':'male', 'Female':'female'}})
Newdata.sex = CFS

changeforemb = pd.DataFrame(data.embarked)  # work on the inconsistency of emb
CFE = changeforemb.replace({'embarked': {'Queenstown':'Q'}})
Newdata.embarked = CFE

In [ ]:
#Store the clean data in a csv file
Newdata.to_csv('NewData.csv')